### ISSUE TITLE
[BUG] [FlyteAdmin] [scheduledWorkflowExecutor] SQS subscriber client stopped working

### ISSUE THREAD

**Issue by rstanevich** [lyft/flyte#198]
**Describe the bug**

Flyteadmin scheduledWorkflowExecutor worked successfully ~2 weeks with no redeployment.

But one day:
- SQS client had been shutted down
- Async Scheduler stopped working
- FlyteAdmin continued running with no scheduledWorkflowExecutor
- Cloudwatch events continued push messages to the queue and it was being increased.

What logs I'd got before the scheduler stopped working:
```
{"json":{"src":"base.go:138"},"level":"info","msg":"Successfully started running the scheduled workflow executor","ts":"2020-03-07T05:39:04Z"}
```
https://github.com/lyft/flyteadmin/blob/60b4c876ea105d4c79e3cad7d56fde6b9c208bcd/pkg/rpc/adminservice/base.go#L138L139
Normally, this log doesn't appear when FlyteAdmin starts. And if I understand correctly this log shouldn't appear because this row is not reachable.
Unfortunately, there is no more logs.

**Expected behavior**

- If is it possible to show the errors in logs from consumer connection if client shutdown
https://github.com/nytimes/gizmo/blob/master/pubsub/pubsub.go#L44
- Retry mechanism for gizmo client or smth else

**Flyte component**
- [+] FlyteAdmin (Control Plane service) UPD: image: docker.io/lyft/flyteadmin:v0.2.1

**To Reproduce**
1. Scheduler config in FlyteAdmin:
```
scheduler:
  eventScheduler:
    scheme: aws
    region: "us-east-1"
    scheduleRole: "arn:aws:iam::{{ AWS_ACCOUNT_ID }}:role/flyte_cron_scheduler_role"
    targetName: "arn:aws:sqs:us-east-1:{{ AWS_ACCOUNT_ID }}:flyte-cron-scheduler-queue"
  workflowExecutor:
    scheme: aws
    region: "us-east-1"
    scheduleQueueName: "flyte-cron-scheduler-queue"
    accountId: "{{ AWS_ACCOUNT_ID }}"  
```
2. Run FlyteAdmin and wait for this message (I don't know what was the reason and how to reproduce it) :) 
```{"json":{"src":"base.go:138"},"level":"info","msg":"Successfully started running the scheduled workflow executor","ts":"2020-03-07T05:39:04Z"}```

**Environment**
**Flyte component**
- [+] Cloud hosted
     * [+] AWS

**Others**
Restarting of the FlyteAdmin pod initialized new scheduledWorkflowExecutor and the SQS events were executed.

Thank you!
