### ISSUE TITLE
[Feature]Log Plugins update to allow templated strings 

### ISSUE THREAD

**Issue by kumare3** [lyft/flyte#549]
**Motivation: Why do you think this is important?**
Today the Log Plugins are very limited. They only support a hardcoded link with couple parameters in the template. This works for some cases, but for many cases this is very limiting. The proposal is to overhaul the logging system to instead take a template URL and defaults in the configuration. A Clear documentation of available variables will help the user design the log string

**Goal: What should the final outcome look like, ideally?**
Admins should be able to update the log plugins so that the Query string is a config value,
e.g. 
The API can remain constant or get updated [here](https://github.com/lyft/flyteidl/blob/master/clients/go/coreutils/logs/logs.go#L9)
but the user can specify log plugins like
```yaml
logs:
    name: CloudWatch
    constants:
            - region: us-east
            - logStream: my-stream
    template_url:  "https://console.aws.amazon.com/cloudwatch/home?region={{ .constants.region }}#logEventViewer:group={{.constants.logStream}};stream=var.log.containers.{{.vars.podName}}_{{.vars.namespace}}_{{.vars.containerName}}-{{.vars.containerID}}.log"
```
Constants are user specified
and Vars are the default variables available in the function.

**Describe alternatives you've considered**
NA

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [x] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**[Optional] Propose: Link/Inline**
NA

**Additional context**

**Is this a blocker for you to adopt Flyte**
Maybe
